name: Daily Crime Prediction Run
on:
  schedule:
    - cron: '0 13 * * *'  # Runs at 1300(1pm) UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    permissions:          # Add permissions block
      contents: write    # Grant write permission to repository contents
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Add token here
          ref: llm_call
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run prediction script
        env:
          MODEL_NAME: "o3-mini"
          API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python ./src/open_source_test_script.py
        
      - name: Commit and push data files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./data/deployed_files/prediction_data.csv
          git add ./data/deployed_files/visualization_data.csv
          git commit -m "Update prediction data $(date +'%Y-%m-%d') [skip ci]"
          git push
