name: Daily Crime Prediction Run
on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3 AM UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run prediction script
        run: python ./src/main.py
        
      - name: Commit and push data files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./data/deployed_files/last_day_input_data.csv
          git add ./data/deployed_files/prediction_data.csv
          git add ./data/deployed_files/visualization_data.csv
          git commit -m "Update prediction data $(date +'%Y-%m-%d') [skip ci]"
          git push